config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'static_page/home'
  get '/help', to: 'static_page#help'
  get '/about', to: 'static_page#about'
  get '/contact', to: 'static_page#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_page#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i
  validates :email, presence: true, length: { maximum: 255 }, format: {with: VALID_EMAIL_REGEX} , uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "Hello World"
  end
  
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to current_user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url

  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if logged_in?
      @user = User.find(params[:id])
    else
      redirect_to login_path
    end
  end
  def new
    @user = User.new
  end
  def index
    if !logged_in?
      redirect_to login_path
    end
      
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome ! You have been signed up!"
      login @user
      redirect_to user_url(@user)
    else
      render 'new'
      flash.alert = "Invalid Inputs"
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    return (!current_user.nil?)
  end
  
  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_shim.html.erb
<footer class = "footer">
  <small>
    <p>Creator : Karthik Vuswanathan</p>
    <a href="http://nickinack.github.io/" target="_blank">Creator's Website</a>
  </small>
  <ul>
    <li><%= link_to "Contact" , contact_path %></li>
  </ul>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <head>
    <title><%= (yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  
  <header class="navbar navbar-expand-lg navbar-light bg-light">
    
      <a class = "navbar-brand">Navbar</a>
      <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active "><%= link_to "Home",   root_path , class: "nav-link" %></li>
        <li class="nav-item active "><%= link_to "Help",   help_path , class: "nav-link" %></li>
        <li class="nav-item active "><%= link_to "About",   about_path , class: "nav-link" %></li>
        <% if logged_in? %>
        <li class="nav-item active "><%= link_to "Log out", logout_path , method: :delete , class: "nav-link"%></li>
        <% else %>
        <li class="nav-item active "><%= link_to "Log in", login_path , class: "nav-link"%></li>
        <% end %>
      </ul>
    
    
  </header>

  <body>
 
    <%= yield %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/shim' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/about.html.erb
<!DOCTYPE html>
<% provide(:title , 'About') %>
<html>

  <body>
    <h1>This is the about-page  of the sample app!</h1>
  </body>
</html>

app/views/static_page/contact.html.erb
<!DOCTYPE html>
<% provide(:title , 'Contact') %>
<html>

  <body>
    <h1>This is the contact-page of the sample app!</h1>
  </body>
</html>

app/views/static_page/help.html.erb
<!DOCTYPE html>
<% provide(:title , 'Help') %>
<html>

  <body>
    <h1 id="helpheading">This is the help-page of the sample app!</h1>
  </body>
</html>

app/views/static_page/home.html.erb
<%= provide(:title , "SampleApp") %>
<div class="center jumbotron">
  <h1 class="text-center">Welcome to the Sample App</h1>

  <h2 class="text-center">
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", id: "signup" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                      "https://rubyonrails.org/" %>

app/views/users/index.html.erb
<h1>You are at the index page of the signup! You will be redirected to the signup page later</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render '/shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
       <div class="user">
       <div class = "img-responsive" id="profile-pic"> <%= gravatar_for @user %> </div>
        <%= @user.name %>
        </div>
      </h1>
    </section>
  </aside>
</div>